SftConfig:
  num_epochs: 2
  learning_rate: 5e-5
  gradient_accumulation_steps: 8
  micro_batch_size: 8

ExpertIterConfig:
  question_batch_size: 1024
  sample_batch_size: 16
  n_ei_steps: 5
  use_all_positive: True