SftConfig:
  model_id: "Qwen/Qwen2.5-0.5B"
  num_epochs: 1
  learning_rate: 5e-5
  gradient_accumulation_steps: 2
  micro_batch_size: 1

ExpertIterConfig:
  question_batch_size: 32
  sample_batch_size: 8
  n_ei_steps: 2
  output_model_dir: "output/expert_iter"