SftConfig:
  num_epochs: 5
  learning_rate: 5e-5
  gradient_accumulation_steps: 8
  micro_batch_size: 8
  max_examples: 2048

ExpertIterConfig:
  question_batch_size: 2048
  sample_batch_size: 8
  n_ei_steps: 5